SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BORDER_POSITIVE_X_OFFSET = 10
BORDER_NEGATIVE_X_OFFSET = 20
BORDER_POSITIVE_Y_OFFSET = 10
BORDER_NEGATIVE_Y_OFFSET = 20

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

POWER_UP_RADIUS = 20
POWER_UP_FONT_SIZE = 25
POWER_UP_MIN_SPAWN_INTERVAL = 10
POWER_UP_MAX_SPAWN_INTERVAL = 20
POWER_UP_MIN_DURATION_INTERVAL = 5
POWER_UP_MAX_DURATION_INTERVAL = 10




